---
# tasks file for k8s4vagrant
- name: requirements
  include_tasks: requirements.yml

- name: setup
  include_tasks: kube-setup.yml


## Workaround

- name: Stop firewalld
  systemd:
    name: firewalld
    state: stopped

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no

- name: Mask firewalld (optional, to ensure it can't be started)
  systemd:
    name: firewalld
    masked: yes

- name: Reload iptables rules
  shell: "iptables-restore < /etc/iptables/rules.v4"
  args:
    executable: /bin/bash