apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbt
  namespace: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lbt
  template:
    metadata:
      labels:
        app: lbt
    spec:
      containers:
      - name: lbt
        image: strm/helloworld-http:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lbt
  namespace: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: lbt
