apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: wordpress
spec:
  containers:
  - name: debug-container
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
    stdin: true
    tty: true
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: kubenode02
